kubectl apply -f namespace.yml
kubectl apply -f evtsrc.yml 
kubectl apply -f identification_command.yml 
kubectl apply -f identification_query.yml 
kubectl apply -f posting_command.yml 
kubectl apply -f posting_query.yml 
kubectl apply -f chats_command.yml 
kubectl apply -f chats_query.yml 
kubectl apply -f ui.yml 
kubectl apply -f ingress.yml 