apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/temp"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: evtsrc-server-deployment
  labels:
    app: evtsrc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evtsrc-server
  template:
    metadata:
      labels:
        app: evtsrc-server
    spec:
      volumes:
        - name: evt-src-db-storage
          persistentVolumeClaim:
            claimName: task-pv-claim          
      containers:
        - name: evtsrc-server
          image: lab0mb4/evtsrc:v0.4.4
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128M"
              cpu: "0.5"
          ports:
            - containerPort: 5515
          volumeMounts:
          - mountPath: "/app/db_files"
            name: evt-src-db-storage
---
apiVersion: v1
kind: Service
metadata:
  name: evtsrc-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5515
  selector:
    app: evtsrc-server
